### PR TITLE
Add small patch for python 3.12 compatibility

### PR DESCRIPTION
**Pull request by hmaarrfk**
xref: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/584
xref: https://github.com/conda-forge/anaconda-client-feedstock/issues/48

cc:  @mbargull

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mbargull** [comment]
Thanks. I'd rather not touch `clyent` at all since it is abandoned anyway.
Let's rather see if https://github.com/Anaconda-Platform/anaconda-client/pull/691 gets merged/released.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
i understand, but it is really 1 line.

That said, it is pretty difficult to test....

**Comment by mbargull** [comment]
> That said, it is pretty difficult to test....

Well, `anaconda-client` is the sole consumer of this -- so if `anaconda-client` work, it works ;P. (And yes, it does.)

> i understand, but it is really 1 line.

Yeah, it was just not worth it for me to deal with re-building this package (we haven't built this for 5-6 years; would need updated `versioneer` and stuff) and upstream `anaconda-client` needed a solution anyway.

**Comment by hmaarrfk** [comment]
ah dam... the versioneer issue...

**Comment by hmaarrfk** [comment]
Now that things are fixed do you think it is worth merging in?

**Comment by mbargull** [comment]
> Now that things are fixed do you think it is worth merging in?

Depends on the meaning of "worth" ;).
Ideally, we'd have `anaconda-client` updated and then archive this repo.
But it would not really hurt, I guess, and also let people create Py3.12 envs with `anaconda-client` before that's updated.

(Normally I'd ask you to add yourself to the maintainers then; but since this is pending deprecation/archival, I don't have a strong opinion on that.)

**Review by mbargull — APPROVED** [review]

**Pull request merged**
